name: dist

on: workflow_dispatch

jobs:
  dist:
    name: Distributable for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install -U pip wheel
          pip install -r requirements_dev.txt
          pip install nuitka
      - name: Create distributable
        run: |
          python -m nuitka --assume-yes-for-downloads --nofollow-import-to=numpy --onefile -o grimlock-${{ matrix.os }} grimlock/__main__.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: grimlock-${{ matrix.os }}
          path: grimlock-${{ matrix.os }}.exe
