name: pynsist

on: workflow_dispatch

jobs:
  dist_windows:
    name: Pynsist Installer for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.10'
          architecture: 'x64'
      - name: Install NSIS using external script
        uses: idleburg/NSIS-Dev@windows-latest
      - name: Install NSIS
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop bucket add extras
          scoop install nsis
      - name: Print NSIS version
        run: makensis -VERSION
      - name: Install dependencies
        run: |
          pip install -U pip wheel
          pip install -r requirements_dev.txt
          pip install pynsist
      - name: Make wheels
        run: |
          pip wheel . -w wheels
      - name: Create installer
        run: |
          pynsist installer.cfg
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Grimlock Installer
          path: /build/nsis/Grimlock_1.0.exe
